#!/bin/bash
# Cursor Token消耗验证脚本

echo "Cursor Token消耗验证"
echo "======================"

echo "1. 请打开Cursor编辑器"
echo "2. 打开项目: /home/cc/桌面/cursor_shujuku/cursor_shujuku"
echo "3. 执行以下步骤验证token消耗:"
echo ""
echo "步骤A: 查看当前token使用量"
echo "  - 点击Cursor左下角账户图标"
echo "  - 选择'使用统计'"
echo "  - 记录各模型的当前使用量"
echo ""
echo "步骤B: 执行测试任务"
echo "  - 打开文件: cursor_quick_test.md"
echo "  - 复制第一个命令到Cursor聊天窗口"
echo "  - 执行并等待完成"
echo "  - 再次查看使用统计"
echo ""
echo "步骤C: 验证消耗"
echo "  - 对比前后token使用量"
echo "  - 确认GPT-5.2 Codex有增量"
echo "  - 重复测试其他模型"
echo ""
echo "如果token没有消耗，请检查:"
echo "  1. 是否使用了正确的/model:命令"
echo "  2. 任务是否足够复杂"
echo "  3. Cursor是否是最新版本"
echo "  4. 账户是否有可用额度"
